name: bountyhunter
version: 0.1.6
author: Joris Hermans <hermansj@gmail.com>
description: A text search engine
homepage: https://github.com/ForceUniverse/bountyhunter
dependencies:
  logging: '>=0.11.0 <0.12.0'
  cargo: '>=0.8.0 <0.9.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.10.1'