name: bountyhunter
version: 0.1.5
author: Joris Hermans <hermansj@gmail.com>
description: A text search engine
homepage: https://github.com/ForceUniverse/bountyhunter
dependencies:
  logging: '>=0.9.0 <0.10.0'
  cargo: '>=0.4.2 <0.5.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.10.1'